### ISSUE TITLE
UTC Document Submission

### ISSUE THREAD

**Issue by tonton-pixel** [tonton-pixel/Unihan-kJapaneseKun-kJapaneseOn-Error-Report#2]
This error report has been successfully submitted and registered as the UTC document [L2/19-321](http://www.unicode.org/L2/L2019/19321-unihan-error-rept.pdf) on Monday, September 30, 2019.

**Comment by wtn** [comment]
Hello Michel,

A Unihan contributor saw your report, and wanted to let you know about the following list of Wiktionary contributions:

https://en.wiktionary.org/w/index.php?title=Special:Contributions/Nanshu&limit=1500

This Wiktionary user corrected many Japanese readings in 2003, but they never got submitted to the Unihan database. If you pursue kJapaneseKun/kJapaneseOn corrections further, they may be of interest.

Also, I hope you will join us on the Unihan email list, where we discuss and coordinate effort on various CJK-related issues for Unicode. It's a low volume list. If you are interested, you can contact then list administrator (Rick McGowan) directly, or I can help you contact him.

Regards,
William

**Comment by tonton-pixel** [comment]
Hello William,

Thanks for the link to the list of Wiktionary contributions. I'll definitely use it to keep improving the corrections.

I'm glad to know that a Unihan mailing list exists; I must say I've been looking for one since [a while ago](https://www.unicode.org/mail-arch/unicode-ml/y2019-m02/0235.html), but to no avail... I just sent by email a subscription request to Rick McGowan...

Regards,
Michel

**Comment by wtn** [comment]
Were you able successfully to join the Unihan list?

**Comment by tonton-pixel** [comment]
Yes, absolutely. I just added my real name to my subscription options, and started to browse through the Unihan mailing list archives.
Thanks for your invitation.

**Comment by wtn** [comment]
You may have seen the message from 2019-07-29 about the Unicode workspace in Slack. It seems that there is more Unihan discussion on Slack than on the email list lately. Please join us there. You can find my email copied on the last message Eiso sent, and I can give you contact information for requesting Slack access.

**Comment by tonton-pixel** [comment]
No, thanks.
